//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo_Não_Funcional_MDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        public int Id { get; set; }
        public string obs { get; set; }
        public string sintomas { get; set; }
        public string diagonostico { get; set; }
        public int PacientesId { get; set; }
        public int DoutoresId { get; set; }
        public System.DateTime data { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual Doutores Doutores { get; set; }
    }
}
