//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo_Não_Funcional_MDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizadores : Pessoas
    {
        public string email { get; set; }
        public string password { get; set; }
        public string funcao { get; set; }
    }
}
